"""widen_rule_section_title_and_slug

Revision ID: 7b47d6cd3a45
Revises: 20260726_0010
Create Date: 2026-07-27 15:22:58.544579
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7b47d6cd3a45'
down_revision: str | None = '20260726_0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Widen rule_sections.title and slug for long 7.9 section headings
    op.alter_column('rule_sections', 'title',
               existing_type=sa.String(500),
               type_=sa.String(2000),
               existing_nullable=False)
    op.alter_column('rule_sections', 'slug',
               existing_type=sa.String(255),
               type_=sa.String(500),
               existing_nullable=False)
    op.alter_column('sync_runs', 'metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rule_sections', 'slug',
               existing_type=sa.String(500),
               type_=sa.String(255),
               existing_nullable=False)
    op.alter_column('rule_sections', 'title',
               existing_type=sa.String(2000),
               type_=sa.String(500),
               existing_nullable=False)
    op.alter_column('sync_runs', 'metadata',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
